/*
  Warnings:

  - The values [TransferSend,TransferReceive,Fee] on the enum `TransactionAction` will be removed. If these variants are still used in the database, this will fail.

*/
-- CreateEnum
CREATE TYPE "TransactionActionType" AS ENUM ('Buy', 'Sell', 'DRIP', 'CashDividend', 'CashDeposit', 'CashWithdrawal', 'CashFee', 'ParcelFee', 'Split', 'FreeAsset', 'TransferOut', 'TransferIn', 'CashInterest', 'CryptoInterest');

-- AlterEnum
BEGIN;
CREATE TYPE "TransactionAction_new" AS ENUM ('Buy', 'Sell', 'DRIP', 'CashDividend', 'CashDeposit', 'CashWithdrawal', 'CashFee', 'ParcelFee', 'Split', 'FreeAsset', 'TransferOut', 'TransferIn', 'CashInterest', 'CryptoInterest');
ALTER TABLE "PortfolioTransaction" ALTER COLUMN "action" TYPE "TransactionAction_new" USING ("action"::text::"TransactionAction_new");
ALTER TYPE "TransactionAction" RENAME TO "TransactionAction_old";
ALTER TYPE "TransactionAction_new" RENAME TO "TransactionAction";
DROP TYPE "TransactionAction_old";
COMMIT;

-- AlterTable
ALTER TABLE "PortfolioTransaction" ADD COLUMN     "fromAccount" TEXT,
ADD COLUMN     "isAutoGenerated" BOOLEAN DEFAULT false,
ADD COLUMN     "toAccount" TEXT;
